name: Build Artifacts

on:
  workflow_dispatch:
  push:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        run: |
          git submodule update --init --recursive          
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
          npm i -g vite
          cd Ecdar-GUI-Web
          npm install
          git submodule update --init --recursive
          cd ..
          cargo install tauri-cli
      - name: cargo build --release
        uses: clechasseur/rs-cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3
        with:
          name: ecdar_app-${{ matrix.os }}
          path: target/release/ecdar_app
          if-no-files-found: error
          retention-days: 7
