name: Check formatting

on:
  workflow_dispatch:
  push:

jobs:
  fmt:
    name: cargo fmt & Clippy lint and check
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install llvm protobuf-compiler
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps
        run: |
          git submodule update --init --recursive          
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
          npm i -g vite
          cd Ecdar-GUI-Web
          npm install
          git submodule update --init --recursive
          cd ..
          cargo install tauri-cli
      - name: cargo fmt --all
        uses: clechasseur/rs-cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: clippy --all-targets --all-features
        uses: clechasseur/rs-clippy-check@v3
        with:
          args: --all-targets --all-features -- -D warnings
